import { useState } from 'react';
import { Table } from './Table';
import type { Column } from './Table';
import type { V8670KpiInputDetail } from '../../types/types';
import { MyMenu } from "../ReusableMenu-RED/MyMenu";
import { Pencil, Copy, Share2, Archive } from "lucide-react";

const ITEMS_PER_PAGE = 15;

const mockData: V8670KpiInputDetail[] = [
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: "test comment",
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2026,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00008203',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'WEALTH',
    orgcode: 'DIV95',
    objid: '00014083',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
  {
    roleid: 'ADMIN',
    orgcode: 'DIV95',
    objid: '00007664',
    kpi: 'AuM Leads for Private&Wealth (€m) (DIV95)',
    kpiYear: 2025,
    grpid: 'SEGM04',
    objmth: 1,
    objmthvalue: 593.0662,
    objcumvalue: null,
    objmthmastervalue: 0,
    dateUpdateValue: null,
    userUpdateValue: null,
    grplabel: 'TOTAL SEGMENT CORPORATE',
    mesureUnit: null,
    mesureLabel: 'EUR Mio EUR (SUM)',
    autoRun: null,
    comments: null,
    objmthvalue1: 0,
    objmthvalueY1: 0,
    manco: null,
  },
]

const menuOptions = [
    {
      label: "Edit",
      icon: <Pencil size={16} />,
      onClick: () => console.log("Edit clicked"),
    },
    {
      label: "Copy",
      icon: <Copy size={16} />,
      onClick: () => console.log("Copy clicked"),
    },
    {
      label: "Share",
      icon: <Share2 size={16} />,
      onClick: () => console.log("Share clicked"),
    },
    {
      label: "Archive",
      icon: <Archive size={16} />,
      onClick: () => console.log("Archive clicked"),
    },
  ];

function KpiTable() {
    const [page, setPage] = useState(1);

    const pageData = mockData.slice((page - 1) * ITEMS_PER_PAGE, page * ITEMS_PER_PAGE);

    const columns: Column<V8670KpiInputDetail>[] = [
      { key: 'kpiYear',           title: 'KPI Year', sortable: true},
      { key: 'kpi',               title: 'KPI to Process', sortable: true },
      { key: 'grplabel',          title: 'Grp Label',      sortable: true },
      { key: 'objmth',            title: 'KPI Month',      sortable: true },
      {
        key: 'objmthvalueY1',
        title: 'Value Month-1',
        sortable: true,
        render: (row) => row.objmthvalueY1?.toString() ?? '-',
      },
      {
        key: 'objmthvalue',
        title: 'Value Month',
        sortable: true,
        render: (row) => row.objmthvalue?.toString() ?? '-',
      },
      {
        key: 'objmthvalue1',
        title: 'Value Year-1',
        sortable: true,
        render: (row) => row.objmthvalue1?.toString() ?? '-',
      },
      {
        key: 'objmthmastervalue',
        title: 'Master Value',
        sortable: true,
        render: (row) => row.objmthmastervalue?.toString() ?? '-',
      },
      { key: 'mesureLabel',       title: 'Units' },
      { key: 'comments',          title: 'Comments' },
    //   {
    //     key: 'kpi',
    //     title: 'EDIT',
    //     render: () => {
    //       return (
    //         <span>
    //           <MyMenu items={menuOptions} direction="top" anchor="start" />
    //         </span>
    //       );
    //     },
    //   },
    ];

    return (
      <div className="overflow">
        <Table<V8670KpiInputDetail>
          data={pageData}
          columns={columns}
          totalItems={mockData.length}
          itemsPerPage={ITEMS_PER_PAGE}
          currentPage={page}
          onPageChange={setPage}
          scrollable
          maxHeight="65vh"
        />
      </div>
    );
}

export default KpiTable;
